### ISSUE TITLE
Move from Guava ListenableFuture to Java 8 CompletableFuture

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo#722]
Guava Futures and ListenableFuture was used for the async commit changes.  Now that we have switched to java 8, should look in to using CompletableFuture.   Also Futures in marked `@Beta` in guava, so it could change in incompatible ways or be dropped in the future.

**Comment by ctubbsii** [comment]
Found this guide to help: https://github.com/krka/java8-future-guide

**Comment by jkosh44** [comment]
Since I just got some experience using CompletableFutures I'd like to give this a shot.

**Comment by keith-turner** [comment]
@jkosh44  this will be a very involved change.  I can assist as needed, let me know if you have any questions.   You already have a feel for CompletableFuture, I would recommend experimenting with Guava ListenableFutures in a stand alone program to get a feel for them.

**Comment by jwonders** [comment]
Hi folks,  I've been lurking around on the mailing lists for awhile as I haven't really had much time to start contributing.  I've been exploring async wrappers around Accumulo in a side project and it makes heavy use of CompletionStage/CompletableFuture.  I figured I'd post a link in case you want to take a look at another implementation for comparison.

https://github.com/jwonders/ax-accumulo

In particular, the [AsyncConditionalWriterImpl][1] might be of interest.

I'm sure this task goes well beyond an AsyncConditionalWriter or AsyncBatchWriter, but hopefully this is worthwhile to look at since there isn't a straight translation from ListenableFuture to CompletableFuture.

[1]: https://github.com/jwonders/ax-accumulo/blob/master/src/main/java/com/jwsphere/accumulo/async/internal/AsyncConditionalWriterImpl.java

**Comment by jkosh44** [comment]
Hey sorry I've had an extremely hectic week and haven't been able to look at this yet. I'm going to start on this tonight. Unless you're asking to work on this jwonders then feel free.

**Comment by keith-turner** [comment]
@jwonders I am not sure if ax-accumulo would be relevant for this PR because I have not had enough time  to look at in depth.  I am really glad you shared because I am very happy to learn about the existence of ax-accumulo.  At some point I would like to add async APIs to Accumulo.  As time permits, I would like to learn from and possibly leverage ax-accumulo's APIs for Accumulo.

**Comment by jwonders** [comment]
@keith-turner I agree it might not be relevant and I'm not familar enough with fluo to know all of the touchpoints for this PR.  Just wanted to point it out as a possible reference if migrating the async writers to CompletableFuture.  I'm also interested in native async APIs in Accumulo because to get the most benefit the implementation needs to be async down to the RPC layer.  The ax-accumulo project is an attempt to explore what is possible right now and understand the points where it that are currently awkward for async interaction which can hopefully inform the development of async Accumulo APIs.  I still need to explore scanners in much more depth.

@jkosh44 Please don't let me get in the way of your plans.  I would be interested in reviewing what you end up with and learning more about fluo's async transactions.

**Comment by jkosh44** [comment]
Did some analysis of where ListenableFuture is used and here's what I found:

Classes that use ListenableFuture:
                ...core/impl/TransactionImpl
                ...core/async/AsyncConditionalWriter
                ...core/oracle/OracleClient
                ...OracleClient.TimeRequest
                ...core/impl/SharedBatchWriter
                ...SharedBatchWriter.MutationBatch
               
 
Functions that use Listenable Futures within TransactionImpl:
                private void beginCommitAsync(CommitData cd, AsyncCommitObserver commitCallback, RowColumn primary)
                private void lockOtherColumns(CommitData cd)
                private void postLockOther(final CommitData cd, Iterator<Result> results)
                private void rollbackOtherLocks(CommitData cd)
                private void rollbackPrimaryLock(CommitData cd)
                private void writeNotificationsAsync(CommitData cd, final long commitTs)
                private void commmitPrimary(CommitData cd, final long commitTs)
                private void deleteLocks(CommitData cd, final long commitTs)
               
SharedBatchWriter.MutationBatch Info:
                constructor:  public MutationBatch(Collection<Mutation> mutations, ListenableFutureTask<Void> lf)
                function that uses ListenableFuture: public void countDown()
               
 
Functions that return Listenable Futures:
                AsynConditionalWriter.appply: public ListenableFuture<Iterator<Result>> apply(Collection<ConditionalMutation> input)
                                Note: This also uses ListeningExecutorService to submit new tasks
                OracleClient.getStampAsync: public ListenableFuture<Stamp> getStampAsync()
                                Note: This also uses ListenableFutureTask to create new tasks
                SharedBatchWriter.writeMutationsAsyncFuture: ListenableFuture<Void> writeMutationsAsyncFuture(Collection<Mutation> ml), ListenableFuture<Void> writeMutationsAsyncFuture(Mutation m)
                                Note: This also uses ListenableFutureTask to create new tasks

**Comment by jkosh44** [comment]
So I wanted to start with changing SharedBatchWriter.MutationBatch since it's the most independent.

Currently it uses ListenableFutureTask.run() to run tasks asynchronously. Since it just inherits that function from FutureTask.run() without overriding it, I think the most straight forward solution would be to replace all occurrences of of ListenableFutureTask with FutureTask.

Alternatively I can change the constructor of MutationBatch to take a Runnable. Then when calling countDown() we call CompletableFuture.runAsync(Runnable).

@keith-turner what do you think?

**Comment by jkosh44** [comment]
Ok so in general the functions of TransactionImpl that use ListenableFutures are of the following form
...
```
ListenableFuture<...> future = ...;
Futures.addCallback(future, new CommitCallback<...>(cd){...}, env.getSharedResources().getAsyncCommitExecutor());
```
...
At a very high level I think the approach I'm going to take is convert it to some along the lines of 
...
```
CompletableFuture<...> future = ...;
future.thenAcceptAsync(_, env.getSharedResources().getAsyncCommitExecutor())
.exceptionally(_)
```
...

Where thenAccept would perform the same action as onSuccess of the callback. And exceptionally would perform the same action as onFail of the callback.

**Comment by keith-turner** [comment]
@jkosh44 I think you are on the right track.  Because I am not deeply familiar with completable future I had to try experimenting in order to evaluate your proposal.  Below are the results of my experiment.

I add the following to AsyncConditionalWriter just to enable me to try writing some code.

```java
  public CompletableFuture<Iterator<Result>> write(Collection<ConditionalMutation> input) {
    return null;
  }
```

Then for [TransactionImpl line 972](https://github.com/apache/fluo/blob/185a1cbfa57ba53896afcc5b1d685aea453e9404/modules/core/src/main/java/org/apache/fluo/core/impl/TransactionImpl.java#L972) I changed it to the following.

```java
 final ConditionalMutation pcm =
        prewrite(cd.prow, cd.pcol, cd.pval, cd.prow, cd.pcol, isTriggerRow(cd.prow));

    CompletableFuture<Iterator<Result>> cfuture = cd.acw.write(Collections.singletonList(pcm));
    cfuture.thenAcceptAsync(result -> {
      try {
        // this method currently throws Exception, so must be caught...
        postLockPrimary(cd, pcm, Iterators.getOnlyElement(result));
      } catch (Exception e) {
        cd.commitObserver.failed(e);
      }
    }, env.getSharedResources().getAsyncCommitExecutor()).exceptionally(exception -> {
      //not sure this really needed... since code above catches exception
      cd.commitObserver.failed(exception);
      return null;
    });
```

Based on this experiment I am left wondering how we could make the code above more concise. The class CommitCallback was created to avoid duplicate code for exception handling.   I feel like we may need something similar for completable future, but not sure.

**Comment by jkosh44** [comment]
What if we had an interface like this (name needs some serious improvement)
`private static interface OnSuccessInterface<V> {
  protected void onSuccess(CommitData cd, V result) throws Exception;
}`

Then we can also have the following method:
`private void addCallback(CompletableFuture<V> cfuture, CommitData cd, OnSuccessInterface onSuccessInterface){
  cfuture.thenAcceptAsync(result -> {
      try {
        // this method currently throws Exception, so must be caught...
        onSuccessInterface.onSuccess(cd, result);
      } catch (Exception e) {
        cd.commitObserver.failed(e);
      }
    }, env.getSharedResources().getAsyncCommitExecutor()).exceptionally(exception -> {
      //not sure this really needed... since code above catches exception
      cd.commitObserver.failed(exception);
      return null;
    });
}`

That way TransactionImpl line 972 can be changed to the following:
`final ConditionalMutation pcm =
        prewrite(cd.prow, cd.pcol, cd.pval, cd.prow, cd.pcol, isTriggerRow(cd.prow));

    CompletableFuture<Iterator<Result>> cfuture = cd.acw.write(Collections.singletonList(pcm));
    addCallBack(cfuture, cd, new OnSuccessInterface<Iterator<Result>> {
      @Override
      protected void onSuccess(CommitData cd, Iterator<Result> result) throws Excption {
        postLockPrimary(cd, pcm, Iterators.getOnlyElement(result));
      }`

**Comment by jkosh44** [comment]
OracleClient and SharedBatchWriter seem to only use and deal with ListenableFutureTask<V>. The only method they seem to call is `create(Runnable runnable, V result)` and `run()` (Which it inherits from FutureTask<V>). Since the ListenableFutureTask<V> class implements ListenableFuture<V> we're able to return ListenableFutureTask<V> when we're expecting a ListenableFuture<V>.

I propose we create the following class and replace all occurrences of ListenableFutureTask<V> with it:
```
public class CompletableFutureTask<V> extends CompletableFuture<V> {
  Runnable runnable;

  private CompletableFutureTask(Runnable runnable){
    this.runnable = runnable;
  }

  public CompletableFutureTask<V> create(Runnable runnable){
    return CompletableFutureTask(runnable);
  }

  public void run(){
    super.runAsync(runnable);
  }

}
```

The ListenableFutureTask<V> class also takes and returns some V result, but every occurrence I saw us using it we just supplied null, so I left it out. I can also add create(Callable callable{...} to keep it consistent but I don't think we ever use it.

**Comment by jwonders** [comment]
I think it might be worth considering using `thenComposeAsync(...)` for the `TransactionImpl` behavior.  It looks like that class chains many asynchronous operations together based on the result of the previous operation.  This is exactly what the `thenCompose(...)` methods are intended for.  The catch is that it would probably require some singificant refactoring as `thenCompose(...)` expects functions that return a `CompletionStage` rather than functions that invoke a callback.  In the long-run I think this would clean up the code and be more idomatic approach.  However, it looks like it would be quite an undertaking based on the complexity of the transaction implementation.

**Comment by keith-turner** [comment]
@jkosh44 the addCallback method looks good.  I gave it a try locally with the example I had yesterday.  I added a type parameter to the method definition as follows.

```java
private <V> void addCallback(CompletableFuture<V> cfuture, CommitData cd, OnSuccessInterface<V> onSuccessInterface){
```
I was able to use a lambda witht the OnSuccessInterface as follows.  So its only two lines, which is nice.

```java
    CompletableFuture<Iterator<Result>> cfuture = cd.acw.write(Collections.singletonList(pcm));
    addCallback(cfuture, cd, (cd2, result) -> postLockPrimary(cd2, pcm, Iterators.getOnlyElement(result)));
```

**Comment by jwonders** [comment]
Assuming the creation of a data class, maybe called `AsyncCommitResult`, that can represent the various outcomes of the async commit, something like the following would be an alternative.

In the end, the chaining might look similar to what @jkosh44 is suggesting except there would not be a need for the `CompletableFutureTask` or the `addCallback` method because the `thenComposeAsync` method already implements the desired behavior.  There would be a bit less indirection as well.

``` java
 private CompletionStage<AsyncCommitResult> deleteLocks(CommitData cd, final long commitTs) {
    ArrayList<Mutation> mutations = new ArrayList<>(updates.size() + 1);
    // snip ---
    // start the finish commit task after the delete locks task completes successfully
    // in this case the finish commit task does not make a decision based on the result
    return env.getSharedResources().getBatchWriter()
            .writeMutationsAsyncCF(mutations)
            .thenComposeAsync(x -> finishCommit(cd, commitTs), executor());
  }

  private CompletionStage<AsyncCommitResult> finishCommit(CommitData cd, long commitTs) {
    ArrayList<Mutation> afterFlushMutations = new ArrayList<>(2);
    // snip ---
    return env.getSharedResources().getBatchWriter()
            .writeMutationsAsyncCF(afterFlushMutations)
            .thenApply(x -> AsyncCommitResult.committed());
  }
```

For the _fail-fast_ cases, it is reasonable to return a completion stage that is immediately failed, and for the synchronous tasks, it is reasonable to just perform them synchronously and then return an already-completed future.

**Comment by keith-turner** [comment]
@jkosh44 re CompletableFutureTask I think it may not be needed.  I am not sure but I think that SharedBatchWriter did the goofy stuff it does because ListenableFuture did not have anything like the complete method.  

I think SharedBatchWriter could do the following.

 * When `writeMutationsAsyncFuture()` is called, create a new CompeltableFuture<Void>.  Put this compfuture and the mutation on the queue for background processing.  Return the compfuture.
 * After the background thread successfully writes some mutations, it can call `complete(null)` on the compfuture that goes with the mutations.

For OracleClient it can do something similar.  Create `CompeltableFuture<Stamp>`, queue it and return it. The background thread can call `complete(stamp)` when it has acquired a stamp for the request.

**Comment by keith-turner** [comment]
@jwonders I like your suggestions relating to `thenComposeAsync`.  When converting the commit process form sync to async one thing I was unhappy with was that the high level logic was spread far and wide.  For the sync code there was one method that drove the entire commit process.  So in essence the high level commit logic could be understood by looking at this method.  When translating to async I could not figure out how to keep this overall logic in one place using ListenableFutures.  So the high level logic was spread across multiple methods.  

It seems that `thenComposeAsync`  may provide a way to pull the commit logic together in the code and I am really in favor of doing that.  I think one way to approach this is to do those changes in a follow on PR after converting the current code to compfuture.  However it could be done in the same PR that converts to compfuture also. I would be happy to review a PR that did either.

**Comment by jwonders** [comment]
@keith-turner It could certainly be done as a follow-on PR.  I've found that it is usually pretty easy to start at the low-level (leafs of the graph of task) and bite off little pieces at a time when migrating to CF or migrating synchronous implementations to async.

**Comment by jkosh44** [comment]
@jwonders @keith-turner I think I'd prefer to first do a direct conversion to CompletableFutures, that way I can get a better understanding of everything that's going on. Then after try and optimize with thenCompose.

@keith-turner  I see what you're saying about the ListenableFutureTasks. I think in general wherever ListenableFuture.run was called we can replace that with a complete call. 

I did some investigating of AsyncConditionalWriter as well. I think the `ListeningExecutorService les` can just be replaced with a normal `ExecutorService es`. In particular `FlouExecutors.newFixedThreadPool(numThreads, "asyncCW")`. The `les.submit(new IterTask(iter, input.size()));` call can be replaced with something like `CompletableFuture.supplyAsync(new IterTask(iter, input.size()).call(), es);`

I'm going to actually play around with some code tonight to try all of this out.

**Comment by keith-turner** [comment]
@jkosh44 replacing `ListeningExecutorService` with `CompletableFuture.supplyAsync()` and regular executor seems like the correct path.  I'm curious to see how it goes in practice.

**Comment by jkosh44** [comment]
So I was able to change AsyncConditionalWriter and OracleClient to use CompletableFutures and changed the TransactionImpl calls accordingly. AsyncConditionalWriter no longer implements AsyncFunction which is part of the Guava package. I was able to run mvn package and mvn verify without any of the tests failing. Are there any tests for commitAsync()?

When changing OracleClient I found that you can't complete a CompletableFuture with a value of null. After some research it seems to be a bug with the CompletableFuture class itself. Seeing how that was sort of a work around anyway I'm going to try and see what else we can do tomorrow. Possibly something with runAsync.

I opened up a pull request here: [WIP - Issue 722](https://github.com/apache/fluo/pull/975 )

**Comment by keith-turner** [comment]
@jkosh44 I ran the following wihtout issue and it printed null
```java
    CompletableFuture<Void> cf = new CompletableFuture<>();
    cf.complete(null);
    System.out.println(cf.get());
```

**Comment by jkosh44** [comment]
@keith-turner I went back to try again and keep running into the same error.
```
[INFO] --- findbugs-maven-plugin:3.0.5:check (find-bugs) @ fluo-core ---
[INFO] BugInstance size is 2
[INFO] Error size is 0
[INFO] Total bugs: 2
[INFO] Null passed for non-null parameter of java.util.concurrent.CompletableFuture.completedFuture(Object) in org.apache.fluo.core.impl.SharedBatchWriter.writeMutationsAsyncFuture(Collection) [org.apache.fluo.core.impl.SharedBatchWriter] At SharedBatchWriter.java:[line 198] NP_NONNULL_PARAM_VIOLATION
[INFO] Null passed for non-null parameter of java.util.concurrent.CompletableFuture.complete(Object) in org.apache.fluo.core.impl.SharedBatchWriter$MutationBatch.countDown() [org.apache.fluo.core.impl.SharedBatchWriter$MutationBatch] At SharedBatchWriter.java:[line 84] NP_NONNULL_PARAM_VIOLATION
[INFO] 
```

Line 84 of `SharedBatchWrited` is the `complete` statement below:
```
public void countDown() {
  if (cdl != null) {
    cdl.countDown();
  }

  if (cf != null) {
    cf.complete(null);
  }
}
```

Line 198 is the `completedFuture` line below:
```
CompletableFuture<Void> writeMutationsAsyncFuture(Collection<Mutation> ml) {
  if (ml.size() == 0) {
    return CompletableFuture.completedFuture(null);
  }

  CompletableFuture<Void> cf = new CompletableFuture<>();
  try {
    MutationBatch mb = new MutationBatch(ml, cf);
    mutQueue.put(mb);
    return cf;
  } catch (Exception e) {
    throw new RuntimeException(e);
  }
}
```

If it makes a difference I only get this error when calling `mvn verify` and not when calling `mvn package`

**Comment by ctubbsii** [comment]
@jkosh44 The error occurs during `mvn verify`, but not `mvn package`, because findbugs runs at the `integration-test` phase of the Maven build lifecycle, which occurs after the `package` phase. See https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

The bug is a false positive. See findbugsproject/findbugs#79 which was fixed only in spotbugs in spotbugs/spotbugs#484, which we have not yet switched to. You can ignore for now, with `-Dfindbugs.skip` when you build. It can also be added to the findbugs exclude-filter file.

**Comment by keith-turner** [comment]
@jkosh44 you may be able to prevent findbugs from triggering with indirection.  Maybe something like the following will throw it off.

```java
  //added to avoid findbugs false positive
  private static final Supplier<Void> NULLS = () -> null;
  
CompletableFuture<Void> writeMutationsAsyncFuture(Collection<Mutation> ml) {
  if (ml.size() == 0) {
    return CompletableFuture.completedFuture(NULLS.get());
  }
```

**Comment by jkosh44** [comment]
Gotcha, when I first came across those pages I misinterpreted them as saying there was a bug in CompletableFutures not Maven. I probably won't have access to my computer until Sunday, so I'll try both of these then.

**Comment by jkosh44** [comment]
@keith-turner The indirection worked, just pushed the fix.

**Comment by jkosh44** [comment]
@jwonders I've been looking at your suggestions and had a question. I'm still unclear as to what AsynCommitResult's purpose is. Can you expands on that for me?

**Comment by jwonders** [comment]
The purpose of `AsyncCommitResult` is to capture the result of the async operation.  Terminal steps would be able to create a concrete value of this result class because they are aware of successful completion or errors.  Intermediate steps would return a future based on additional composed async steps.

In the code I had posted, the `finishCommit` method is a terminal step that returns the `committed()` status upon successful completion.  The `deleteLocks` is an intermediate step that does its work then composes the result with the `finishCommit` step.  Some steps might return immediately upon exceptional conditions and perform composition on normal conditions.
