### ISSUE TITLE
Stop using system.exit for fluo commands

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo#983]
See https://github.com/apache/fluo/pull/982/files/a4bf630e6de398a848d412f6ca1a11bfb4dee6fa#r158413399

**Comment by keith-turner** [comment]
From some problems I do not really want to see a stack trace.   For example currently some commands currently detect when the oracle is not running and print a nice error message.  For this case I personally would not like to see a stack trace.   However if a command throws an NPE I would like to see that stack trace.   To deal with this I propose the following.

 * Create FluoCommandException that extends Runtime exception.
 * Common code is used to run all commands and it does the following :
   * Catches FluoCommandException and logs just the message at error and the stack trace at debug.
   * Catches Exception and logs message and trace at error level.
 * In command code throw FluoCommandException in places where it makes sense.

**Comment by ctubbsii** [comment]
So, without fully understanding all the code which this could impact (so, I could be totally off base with these suggestions), I have a few thoughts.

I think there are a few goals:

1. Make the code friendly to execute by a container/wrapping UI without calling `System.exit()`
2. Have a convenient way to catch exceptions (maybe just certain expected ones), print a standard error message and exit with a non-zero exit code.

The easiest way to do this is to have some sort of `exec() throws FluoCommandException` method which `main()` trivially wraps to handle exceptions. We could add a `--debug` option to control whether `main()` shows the stack trace or suppresses them. `main()` should consistently call `System.exit()` whether or not it is zero or non-zero.

As for logging, I'm not sure it makes sense to do any logging from a CLI. CLI which is intended to be run by users should use the console.

**Comment by alanblueshift** [comment]
What if the command module were implemented like a command pattern (http://www.oodesign.com/command-pattern.html). We could reuse the commands in API's, UI and so on...

**Comment by jkosh44** [comment]
Is this something people are still interested in? I was thinking of taking a look at the command module and the command pattern and maybe putting together a POC or something.

**Comment by ctubbsii** [comment]
> Is this something people are still interested in? I was thinking of taking a look at the command module and the command pattern and maybe putting together a POC or something.

Yes. I think avoiding System.exit is still a good idea.

**Comment by jkosh44** [comment]
I've been looking through the command code and I have a couple of questions/comments for anyone that may have worked on the code and knows the answer.
- Some of the commands currently seem to end by returning or letting exceptions propagate to main, while others explicitly call System.exit. I'm wondering if this was an intentional decision or just the result of multiple developers working on it at different times?
- Some commands use a Logger while others print directly to System.out and System.err. I'm also wondering if this was an intentional decision or just the result of multiple developers working on it at different times?
-  On a similar subject to the last point, I think some thought needs to go into Logger vs System.out/System.err. If the command is being called by a UI or API then we probably want to log to a Logger. However if it's being called by the CLI then we probably want to log to System.out/System.err. How do we make this determination? I haven't really given this much thought yet. Might be something to consider as part of a separate issue/PR.
- There doesn't seem to be a lot of tests in the command module. I may try and add some as part of this issue depending on the complexity. I'm thinking most meaningful tests will have to be integration tests though.

**Comment by ctubbsii** [comment]
@jkosh44 The inconsistency is almost certainly not intentional, but probably technical debt incurred by developing at different times (and perhaps by different people).

I agree with you about some thought needing to be put in to whether `System.out` and `System.err` or `Logger` is used. I concur with your demarcation based on user-interactivity via CLI or not, but haven't looked into it to see if there are any potential snags with that.
